name: Build & Release
description: Build and release the UI bundle for use with Antora.

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: miterra-docs-ui-build
  cancel-in-progress: false

jobs:
  build-release:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.head_commit.message, '[Release]')
    runs-on: ubuntu-latest
    env:
      msg: ${{ (github.event_name == 'workflow_dispatch') && '[Action invoked manually]' || github.event.head_commit.message }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Make UI bunble
      run: |
        SOURCEMAPS=true npx gulp bundle
        mv ./build/ui-bundle.zip ./build/miterra-site-ui-bundle.zip
        echo "datetime=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_ENV
                
    - name: Get next version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        scheme: calver

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        make_latest: true
        name: ${{ steps.version.outputs.v-version }}
        tag_name: ${{ steps.version.outputs.v-version }}
        body: |
          Release ${{ steps.version.outputs.v-version }} generated by GitHub Actions on ${{ env.datetime }}.
          Commit message: ${{ env.msg }}
        files: ./build/miterra-site-ui-bundle.zip
        fail_on_unmatched_files: true

    # ----------------------------------------
    # Trigger site rebuild
    - name: Generate GitHub App installation access token (IAT)
      id: generate_iat
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.BOT_APP_ID }}
        private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Trigger workflow on miterra-site
      uses: actions/github-script@v7
      with:
        github-token: ${{ steps.generate_iat.outputs.token }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: '${{ github.repository_owner }}',
            repo: 'miterra-site',
            workflow_id: 'build-publish.yml',
            ref: 'main',
            inputs: {
              source_repo: context.repo.repo,
              source_message: '${{ env.msg }}',
            }
          })
